name: mmdetection
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - brotli-python=1.0.9
  - ca-certificates=2024.11.26
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.8.20
  - cuda-cccl=12.6.77
  - cuda-cccl_win-64=12.6.77
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.6.77
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - debugpy=1.8.5
  - decorator=5.1.1
  - executing=2.1.0
  - freetype=2.12.1
  - gmpy2=2.1.2
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - jinja2=3.1.4
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lcms2=2.12
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.7.77
  - libcurand-dev=10.3.7.77
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - nest-asyncio=1.6.0
  - networkx=3.1
  - openjpeg=2.5.2
  - openssl=3.4.0
  - packaging=24.2
  - parso=0.8.4
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.0.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.8.20
  - python_abi=3.8
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyzmq=26.2.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - sympy=1.13.2
  - tbb=2021.8.0
  - traitlets=5.14.3
  - ucrt=10.0.22621.0
  - vc=14.40
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.13
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - addict==2.4.0
      - albucore==0.0.17
      - albumentations==1.4.18
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - attrs==24.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cffi==1.17.1
      - click==8.1.7
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==44.0.0
      - cycler==0.12.1
      - defusedxml==0.7.1
      - docopt==0.6.2
      - eval-type-backport==0.2.2
      - fairscale==0.4.13
      - fastjsonschema==2.21.1
      - filelock==3.14.0
      - fonttools==4.55.2
      - imageio==2.35.1
      - importlib-resources==6.4.5
      - ipython==8.12.3
      - jedi==0.19.2
      - jmespath==0.10.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mistune==3.0.2
      - model-index==0.1.11
      - nbclient==0.10.1
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - numpy==1.24.4
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - pipreqs==0.5.0
      - pkgutil-resolve-name==1.3.10
      - pycocotools==2.0.7
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pywavelets==1.4.1
      - pywin32==308
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.28.2
      - rich==13.4.2
      - rpds-py==0.20.1
      - scikit-image==0.21.0
      - scipy==1.10.1
      - setuptools==60.2.0
      - shapely==2.0.6
      - six==1.17.0
      - soupsieve==2.6
      - stack-data==0.6.3
      - tabulate==0.9.0
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - tifffile==2023.7.10
      - tinycss2==1.4.0
      - tomli==2.2.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - tornado==6.4.2
      - tqdm==4.65.2
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==1.26.20
      - webencodings==0.5.1
      - yapf==0.43.0
      - yarg==0.1.9
      - zipp==3.20.2
